// change
export const ENTITY_TYPE_CHANGE_NAME = 'BACKEND/ENTITY_TYPE/ENTITY_TYPE_CHANGE_NAME';
export const ENTITY_TYPE_CHANGE_DESCRIPTION = 'BACKEND/ENTITY_TYPE/ENTITY_TYPE_CHANGE_DESCRIPTION';
export const ENTITY_TYPE_CHANGE_EXTRACT = 'BACKEND/ENTITY_TYPE/ENTITY_TYPE_CHANGE_EXTRACT';
export const CHANGE_ENTITY_TYPE = 'BACKEND/ENTITY_TYPE/CHANGE_ENTITY_TYPE';

// edit ENTITY_TYPE
export const ENTITY_TYPE_TOGGLE = 'BACKEND/ENTITY_TYPE/ENTITY_TYPE_TOGGLE';
export const ENTITY_TYPE_EDIT_REQUEST = 'BACKEND/ENTITY_TYPE/ENTITY_TYPE_EDIT_REQUEST';
export const ENTITY_TYPE_EDIT_SUCCESS = 'BACKEND/ENTITY_TYPE/ENTITY_TYPE_EDIT_SUCCESS';
export const ENTITY_TYPE_EDIT_FAILURE = 'BACKEND/ENTITY_TYPE/ENTITY_TYPE_EDIT_FAILURE';

// get ENTITY_TYPE
export const GET_ENTITY_TYPE_REQUEST = 'BACKEND/ENTITY_TYPE/GET_ENTITY_TYPE_REQUEST';
export const GET_ENTITY_TYPE_SUCCESS = 'BACKEND/ENTITY_TYPE/GET_ENTITY_TYPE_SUCCESS';
export const GET_ENTITY_TYPE_FAILURE = 'BACKEND/ENTITY_TYPE/GET_ENTITY_TYPE_FAILURE';

// delete ENTITY_TYPE
export const ENTITY_TYPE_DELETE_REQUEST = 'BACKEND/ENTITY_TYPE/ENTITY_TYPE_DELETE_REQUEST';
export const ENTITY_TYPE_DELETE_SUCCESS = 'BACKEND/ENTITY_TYPE/ENTITY_TYPE_DELETE_SUCCESS';
export const ENTITY_TYPE_DELETE_FAILURE = 'BACKEND/ENTITY_TYPE/ENTITY_TYPE_DELETE_FAILURE';

// load ENTITY_TYPE request
export const LOAD_ENTITY_TYPE_REQUEST = 'BACKEND/ENTITY_TYPE/LOAD_ENTITY_TYPE_REQUEST';
export const LOAD_ENTITY_TYPE_SUCCESS = 'BACKEND/ENTITY_TYPE/LOAD_ENTITY_TYPE_SUCCESS';
export const LOAD_ENTITY_TYPE_FAILURE = 'BACKEND/ENTITY_TYPE/LOAD_ENTITY_TYPE_FAILURE';

// table action
export const CHANGE_SEARCH = 'BACKEND/ENTITY_TYPE/CHANGE_SEARCH';
export const CHANGE_PAGE = 'BACKEND/ENTITY_TYPE/CHANGE_PAGE';
export const CHANGE_SIZE_PER_PAGE = 'BACKEND/ENTITY_TYPE/CHANGE_SIZE_PER_PAGE';
export const CHANGE_ORDER_COLUMN = 'BACKEND/ENTITY_TYPE/CHANGE_ORDER_COLUMN';
export const CHANGE_ORDER = 'BACKEND/ENTITY_TYPE/CHANGE_ORDER';
