// change
export const INTENT_CHANGE_NAME = 'BACKEND/Intent/INTENT_CHANGE_NAME';
export const INTENT_CHANGE_DESCRIPTION = 'BACKEND/Intent/INTENT_CHANGE_DESCRIPTION';
export const CHANGE_INTENT = 'BACKEND/Intent/CHANGE_INTENT';

// edit intent
export const INTENT_TOGGLE = 'BACKEND/Intent/INTENT_TOGGLE';
export const INTENT_EDIT_REQUEST = 'BACKEND/Intent/INTENT_EDIT_REQUEST';
export const INTENT_EDIT_SUCCESS = 'BACKEND/Intent/INTENT_EDIT_SUCCESS';
export const INTENT_EDIT_FAILURE = 'BACKEND/Intent/INTENT_EDIT_FAILURE';

// get intent
export const GET_INTENT_REQUEST = 'BACKEND/Intent/GET_INTENT_REQUEST';
export const GET_INTENT_SUCCESS = 'BACKEND/Intent/GET_INTENT_SUCCESS';
export const GET_INTENT_FAILURE = 'BACKEND/Intent/GET_INTENT_FAILURE';

// delete intent
export const INTENT_DELETE_REQUEST = 'BACKEND/Intent/INTENT_DELETE_REQUEST';
export const INTENT_DELETE_SUCCESS = 'BACKEND/Intent/INTENT_DELETE_SUCCESS';
export const INTENT_DELETE_FAILURE = 'BACKEND/Intent/INTENT_DELETE_FAILURE';



// load intent request
export const LOAD_INTENT_REQUEST = 'BACKEND/Intent/LOAD_INTENT_REQUEST';
export const LOAD_INTENT_SUCCESS = 'BACKEND/Intent/LOAD_INTENT_SUCCESS';
export const LOAD_INTENT_FAILURE = 'BACKEND/Intent/LOAD_INTENT_FAILURE';


// table action
export const CHANGE_SEARCH = 'BACKEND/Intent/CHANGE_SEARCH';
export const CHANGE_PAGE = 'BACKEND/Intent/CHANGE_PAGE';
export const CHANGE_SIZE_PER_PAGE = 'BACKEND/Intent/CHANGE_SIZE_PER_PAGE';
export const CHANGE_ORDER_COLUMN = 'BACKEND/Intent/CHANGE_ORDER_COLUMN';
export const CHANGE_ORDER = 'BACKEND/Intent/CHANGE_ORDER';

export const INTENT_SELECT_LIST_REQUEST = 'BACKEND/Intent/INTENT_SELECT_LIST_REQUEST';
export const INTENT_SELECT_LIST_SUCCESS = 'BACKEND/Intent/INTENT_SELECT_LIST_SUCCESS';
export const INTENT_SELECT_LIST_FAILURE = 'BACKEND/Intent/INTENT_SELECT_LIST_FAILURE';
export const CHANGE_SELECT_INTENT_ID = 'BACKEND/Intent/CHANGE_SELECT_INTENT_ID';


// -------------response 
export const RESPONSE_DETAIL_CHANGE_TEXT = 'BACKEND/Intent/RESPONSE_DETAIL_CHANGE_TEXT';
export const RESPONSE_DETAIL_CHANGE_IMAGE = 'BACKEND/Intent/RESPONSE_DETAIL_CHANGE_IMAGE';
export const RESPONSE_DETAIL_CHANGE_TYPE = 'BACKEND/Intent/RESPONSE_DETAIL_CHANGE_TYPE';

export const RESPONSE_ADD = 'BACKEND/Intent/RESPONSE_ADD';
export const RESPONSE_COLLAPSE = 'BACKEND/Intent/RESPONSE_COLLAPSE';
export const RESPONSE_ADD_REQUEST = 'BACKEND/Intent/RESPONSE_ADD_REQUEST';
export const RESPONSE_ADD_FAILURE = 'BACKEND/Intent/RESPONSE_ADD_FAILURE';
export const RESPONSE_ADD_SUCCESS = 'BACKEND/Intent/RESPONSE_ADD_SUCCESS';

// EDIT RESPONSE
export const RESPONSE_TOGGLE = 'BACKEND/Intent/RESPONSE_TOGGLE';
export const RESPONSE_EDIT_REQUEST = 'BACKEND/Intent/RESPONSE_EDIT_REQUEST';
export const RESPONSE_EDIT_FAILURE = 'BACKEND/Intent/RESPONSE_EDIT_FAILURE';
export const RESPONSE_EDIT_SUCCESS = 'BACKEND/Intent/RESPONSE_EDIT_SUCCESS';

//get response
export const GET_RESPONSE_REQUEST = 'BACKEND/Intent/GET_RESPONSE_REQUEST';
export const GET_RESPONSE_SUCCESS = 'BACKEND/Intent/GET_RESPONSE_SUCCESS';
export const GET_RESPONSE_FAILURE = 'BACKEND/Intent/GET_RESPONSE_SUCCESS';

// delete response
export const RESPONSE_DELETE_REQUEST = 'BACKEND/Intent/RESPONSE_DELETE_REQUEST';
export const RESPONSE_DELETE_SUCCESS = 'BACKEND/Intent/RESPONSE_DELETE_SUCCESS';
export const RESPONSE_DELETE_FAILURE = 'BACKEND/Intent/RESPONSE_DELETE_FAILURE';

// load response
export const LOAD_RESPONSE_REQUEST = 'BACKEND/Intent/LOAD_RESPONSE_REQUEST';
export const LOAD_RESPONSE_SUCCESS = 'BACKEND/Intent/LOAD_RESPONSE_SUCCESS';
export const LOAD_RESPONSE_FAILURE = 'BACKEND/Intent/LOAD_RESPONSE_FAILURE';

export const CHANGE_RESPONSE = 'BACKEND/Intent/CHANGE_RESPONSE';
export const CHANGE_RESPONSE_DETAIL = 'BACKEND/Intent/CHANGE_RESPONSE_DETAIL';
export const RESPONSE_DETAIL_ADD = 'BACKEND/Intent/RESPONSE_DETAIL_ADD';
//export const RESPONSE_DETAIL_CHANGE_TEXT = 'BACKEND/Intent/RESPONSE_DETAIL_CHANGE_TEXT';
export const RESPONSE_DETAIL_ADD_REQUEST = 'BACKEND/Intent/RESPONSE_DETAIL_ADD_REQUEST';
export const RESPONSE_DETAIL_ADD_SUCCESS = 'BACKEND/Intent/RESPONSE_DETAIL_ADD_SUCCESS';
export const RESPONSE_DETAIL_ADD_FAILURE = 'BACKEND/Intent/RESPONSE_DETAIL_ADD_FAILURE';

export const RESPONSE_DETAIL_EDIT_REQUEST = 'BACKEND/Intent/RESPONSE_DETAIL_EDIT_REQUEST';
export const RESPONSE_DETAIL_EDIT_SUCCESS = 'BACKEND/Intent/RESPONSE_DETAIL_EDIT_SUCCESS';
export const RESPONSE_DETAIL_EDIT_FAILURE = 'BACKEND/Intent/RESPONSE_DETAIL_EDIT_FAILURE';

export const LOAD_RESPONSE_DETAIL_REQUEST = 'BACKEND/Intent/LOAD_RESPONSE_DETAIL_REQUEST';
export const LOAD_RESPONSE_DETAIL_SUCCESS = 'BACKEND/Intent/LOAD_RESPONSE_DETAIL_SUCCESS';
export const LOAD_RESPONSE_DETAIL_FAILURE = 'BACKEND/Intent/LOAD_RESPONSE_DETAIL_FAILURE';

export const RESPONSE_DETAIL_DELETE_REQUEST = 'BACKEND/Intent/RESPONSE_DETAIL_DELETE_REQUEST';
export const RESPONSE_DETAIL_DELETE_SUCCESS = 'BACKEND/Intent/RESPONSE_DETAIL_DELETE_SUCCESS';
export const RESPONSE_DETAIL_DELETE_FAILURE = 'BACKEND/Intent/RESPONSE_DETAIL_DELETE_FAILURE';

export const GET_RESPONSE_DETAIL_REQUEST = 'BACKEND/Intent/GET_RESPONSE_DETAIL_REQUEST';
export const GET_RESPONSE_DETAIL_SUCCESS = 'BACKEND/Intent/GET_RESPONSE_DETAIL_SUCCESS';
export const GET_RESPONSE_DETAIL_FAILURE = 'BACKEND/Intent/GET_RESPONSE_DETAIL_FAILURE';

export const CHANGE_IS_ENABLE_ADD_RESPONSE = 'BACKEND/Intent/CHANGE_IS_ENABLE_ADD_RESPONSE';
export const CHANGE_IS_ENABLE_ADD_RESPONSE_DETAIL = 'BACKEND/Intent/CHANGE_IS_ENABLE_ADD_RESPONSE_DETAIL';

export const UPLOAD_RESPONSE_DETAIL_IMAGE_REQUEST = 'BACKEND/Intent/UPLOAD_RESPONSE_DETAIL_IMAGE_REQUEST';
export const UPLOAD_RESPONSE_DETAIL_IMAGE_SUCCESS = 'BACKEND/Intent/UPLOAD_RESPONSE_DETAIL_IMAGE_SUCCESS';
export const UPLOAD_RESPONSE_DETAIL_IMAGE_FAILURE = 'BACKEND/Intent/UPLOAD_RESPONSE_DETAIL_IMAGE_FAILURE';
