using System;
using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Databay.Chatbot.BotConfiguration.Api.Model
{
    public class Bot
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

	    public string Name { get; set; }

		public string Description { get; set; }

		public ObjectId CreatedBy { get; set; }

	    public ObjectId ModifiedBy { get; set; } = new ObjectId();

		public List<User> Users { get; set; } = new List<User>();

	    public List<Intent> Intents { get; set; } = new List<Intent>();

	    public List<EntityType> EntityTypes { get; set; } = new List<EntityType>();

		[BsonDateTimeOptions]
		public DateTime CreatedDate { get; set; } = DateTime.Now;

		[BsonDateTimeOptions]
        public DateTime ModifiedDate { get; set; } = DateTime.MinValue;
    }
}
