using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Databay.Chatbot.BotConfiguration.Api.Model
{
    public class Entity
	{
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public string Name { get; set; }

		public ObjectId EntityTypeId { get; set; }

		public string Description { get; set; }

		public ObjectId CreatedBy { get; set; }

		[BsonDateTimeOptions]
		public DateTime CreatedDate { get; set; } = DateTime.Now;

		public ObjectId ModifiedBy { get; set; } = new ObjectId();

		[BsonDateTimeOptions]
		public DateTime ModifiedDate { get; set; } = DateTime.MinValue;
	}
}
