using System;
using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Databay.Chatbot.BotConfiguration.Api.Model
{
	public class Response
	{
		[BsonId]
		// standard BSonId generated by MongoDb
		public ObjectId InternalId { get; set; }

		public List<ResponseDetail> ResponseDetails { get; set; } = new List<ResponseDetail>();

		public bool IsCreated { get; set; }

		public ObjectId CreatedBy { get; set; }

		[BsonDateTimeOptions]
		public DateTime CreatedDate { get; set; } = DateTime.Now;

		public ObjectId ModifiedBy { get; set; } = new ObjectId();

		[BsonDateTimeOptions]
		public DateTime ModifiedDate { get; set; } = DateTime.MinValue;
	}
}
