


export const OLD_PASSWORD_CHANGE = 'BACKEND/ChangePassword/OLD_PASSWORD_CHANGE';
export const NEW_PASSWORD_CHANGE = 'BACKEND/ChangePassword/NEW_PASSWORD_CHANGE';
export const CONFIRM_PASSWORD_CHANGE = 'BACKEND/ChangePassword/CONFIRM_PASSWORD_CHANGE';

export const FORGOT_PASSWORD_UPDATE_REQUEST = 'BACKEND/ChangePassword/FORGOT_PASSWORD_UPDATE_REQUEST';
export const FORGOT_PASSWORD_UPDATE_SUCCESS = 'BACKEND/ChangePassword/FORGOT_PASSWORD_UPDATE_SUCCESS';
export const FORGOT_PASSWORD_UPDATE_FAILURE = 'BACKEND/ChangePassword/FORGOT_PASSWORD_UPDATE_FAILURE';
export const HIDDEN_PASSWORD = 'BACKEND/ChangePassword/HIDDEN_PASSWORD';
