//change
export const PATTERN_CHANGE_TEMPLATESENTENCE = 'BACKEND/Pattern/PATTERN_CHANGE_TEMPLATESENTENCE';
export const CHANGE_PATTERN = 'BACKEND/Pattern/CHANGE_PATTERN';

//intent
export const PATTERN_INTENT_SELECT_LIST_REQUEST = 'BACKEND/Pattern/INTENT_SELECT_LIST_REQUEST';
export const PATTERN_INTENT_SELECT_LIST_SUCCESS = 'BACKEND/Pattern/INTENT_SELECT_LIST_SUCCESS';
export const PATTERN_INTENT_SELECT_LIST_FAILURE = 'BACKEND/Pattern/INTENT_SELECT_LIST_FAILURE';
export const PATTERN_CHANGE_SELECT_INTENT_ID = 'BACKEND/Pattern/CHANGE_SELECT_INTENT_ID';

//edit pattern
export const PATTERN_TOGGLE = 'BACKEND/Pattern/PATTERN_TOGGLE';
export const PATTERN_EDIT_REQUEST = 'BACKEND/Pattern/PATTERN_EDIT_REQUEST';
export const PATTERN_EDIT_SUCCESS = 'BACKEND/Pattern/PATTERN_EDIT_SUCCESS';
export const PATTERN_EDIT_FAILURE = 'BACKEND/Pattern/PATTERN_EDIT_FAILURE';


//get pattern

export const GET_PATTERN_REQUEST = 'BACKEND/Pattern/GET_PATTERN_REQUEST';
export const GET_PATTERN_SUCCESS = 'BACKEND/Pattern/GET_PATTERN_SUCCESS';
export const GET_PATTERN_FAILURE = 'BACKEND/Pattern/GET_PATTERN_FAILURE';

// delete  pattern
export const PATTERN_DELETE_REQUEST = 'BACKEND/Pattern/PATTERN_DELETE_REQUEST';
export const PATTERN_DELETE_SUCCESS = 'BACKEND/Pattern/PATTERN_DELETE_SUCCESS';
export const PATTERN_DELETE_FAILURE = 'BACKEND/Pattern/PATTERN_DELETE_FAILURE';

// load pattern request
export const LOAD_PATTERN_REQUEST = 'BACKEND/Pattern/LOAD_PATTERN_REQUEST';
export const LOAD_PATTERN_SUCCESS = 'BACKEND/Pattern/LOAD_PATTERN_SUCCESS';
export const LOAD_PATTERN_FAILURE = 'BACKEND/Pattern/LOAD_PATTERN_FAILURE';

// table action
export const CHANGE_SEARCH = 'BACKEND/Pattern/CHANGE_SEARCH';
export const CHANGE_PAGE = 'BACKEND/Pattern/CHANGE_PAGE';
export const CHANGE_SIZE_PER_PAGE = 'BACKEND/Pattern/CHANGE_SIZE_PER_PAGE';
export const CHANGE_ORDER_COLUMN = 'BACKEND/Pattern/CHANGE_ORDER_COLUMN';
export const CHANGE_ORDER = 'BACKEND/Pattern/CHANGE_ORDER';


export const GET_SELECTION_TEXT = 'BACKEND/Pattern/GET_SELECTION_TEXT';
export const ENTITY_ADD_TEXT = 'BACKEND/Pattern/ENTITY_ADD_TEXT';
export const ENTITY_ADD_REQUEST = 'BACKEND/Pattern/ENTITY_ADD_REQUEST';

export const ENTITY_ADD_SUCCESS = 'BACKEND/Pattern/ENTITY_ADD_SUCCESS';
export const ENTITY_ADD_FAILURE = 'BACKEND/Pattern/ENTITY_ADD_FAILURE';

export const GET_ENTITY_FROM_LIST = 'BACKEND/Pattern/GET_ENTITY_FROM_LIST';
export const GET_INTENT_ID = 'BACKEND/Pattern/GET_INTENT_ID';

//export const CHANGE_ENTITY = 'BACKEND/Pattern/CHANGE_ENTITY';
export const CHANGE_ENTITY_TYPE = 'BACKEND/Pattern/CHANGE_ENTITY_TYPE';
export const LOAD_ENTITY_TYPE_REQUEST = 'BACKEND/Pattern/LOAD_ENTITY_TYPE_REQUEST';
export const LOAD_ENTITY_TYPE_SUCCESS = 'BACKEND/Pattern/LOAD_ENTITY_TYPE_SUCCESS';
export const LOAD_ENTITY_TYPE_FAILURE = 'BACKEND/Pattern/LOAD_ENTITY_TYPE_FAILURE';

export const LOAD_ENTITY_REQUEST = 'BACKEND/Pattern/LOAD_ENTITY_REQUEST';
export const LOAD_ENTITY_SUCCESS = 'BACKEND/Pattern/LOAD_ENTITY_SUCCESS';
export const LOAD_ENTITY_FAILURE = 'BACKEND/Pattern/LOAD_ENTITY_FAILURE';



export const DELETE_ENTITY_REQUEST = 'BACKEND/Pattern/DELETE_ENTITY_REQUEST';
export const DELETE_ENTITY_SUCCESS = 'BACKEND/Pattern/DELETE_ENTITY_SUCCESS';
export const DELETE_ENTITY_FAILURE = 'BACKEND/Pattern/DELETE_ENTITY_FAILURE';