// change tutorial bot
//export const TUTORIAL_CHANGE_BUSINESS_FIELD = 'BACKEND/Tutorial/TUTORIAL_CHANGE_BUSINESS_FIELD';
//export const TUTORIAL_CHANGE_STEP = 'BACKEND/Tutorial/TUTORIAL_CHANGE_STEP';
export const TUTORIAL_HANDLE_NEXT = 'BACKEND/Tutorial/TUTORIAL_HANDLE_NEXT';
export const TUTORIAL_CHANGE_STYLE = 'BACKEND/Tutorial/TUTORIAL_CHANGE_STYLE';

//change tutorial bot
export const TUTORIAL_CHANGE_BOT_NAME = 'BACKEND/Tutorial/TUTORIAL_CHANGE_BOT_NAME';
export const TUTORIAL_CHANGE_BOT_DESCRIPTION = 'BACKEND/Tutorial/TUTORIAL_CHANGE_BOT_DESCRIPTION';
//export const TUTORIAL_CHANGE_BOT = 'BACKEND/Tutorial/TUTORIAL_CHANGE_BOT';

//add tutorial bot
export const TUTORIAL_ADD_BOT_REQUEST = 'BACKEND/Tutorial/TUTORIAL_ADD_BOT_REQUEST';
export const TUTORIAL_ADD_BOT_SUCCESS = 'BACKEND/Tutorial/TUTORIAL_ADD_BOT_SUCCESS';
export const TUTORIAL_ADD_BOT_FAILURE = 'BACKEND/Tutorial/TUTORIAL_ADD_BOT_FAILURE';

//add intent
export const INTENT_CHANGE_NAME = 'BACKEND/Tutorial/INTENT_CHANGE_NAME';

export const ADD_INTENT_REQUEST = 'BACKEND/Tutorial/ADD_INTENT_REQUEST';
export const ADD_INTENT_SUCCESS = 'BACKEND/Tutorial/ADD_INTENT_SUCCESS';
export const ADD_INTENT_FAILURE = 'BACKEND/Tutorial/ADD_INTENT_FAILURE';

//add pattern
export const PATTERN_CHANGE_TEMPLATESENTENCE = 'BACKEND/Tutorial/PATTERN_CHANGE_TEMPLATESENTENCE';

export const ADD_PATTERN_REQUEST = 'BACKEND/Tutorial/ADD_PATTERN_REQUEST';
export const ADD_PATTERN_SUCCESS = 'BACKEND/Tutorial/ADD_PATTERN_SUCCESS';
export const ADD_PATTERN_FAILURE = 'BACKEND/Tutorial/ADD_PATTERN_FAILURE';

//add entity type
export const ENTITYTYPE_CHANGE_NAME = 'BACKEND/Tutorial/ENTITYTYPE_CHANGE_NAME';

export const ADD_ENTITYTYPE_REQUEST = 'BACKEND/Tutorial/ADD_ENTITYTYPE_REQUEST';
export const ADD_ENTITYTYPE_SUCCESS = 'BACKEND/Tutorial/ADD_ENTITYTYPE_SUCCESS';
export const ADD_ENTITYTYPE_FAILURE = 'BACKEND/Tutorial/ADD_ENTITYTYPE_FAILURE';

//select entity
export const GET_SELECTION_TEXT = 'BACKEND/Tutorial/GET_SELECTION_TEXT';
export const ENTITY_ADD_TEXT = 'BACKEND/Tutorial/ENTITY_ADD_TEXT';

export const ENTITY_ADD_REQUEST = 'BACKEND/Tutorial/ENTITY_ADD_REQUEST';
export const ENTITY_ADD_SUCCESS = 'BACKEND/Tutorial/ENTITY_ADD_SUCCESS';
export const ENTITY_ADD_FAILURE = 'BACKEND/Tutorial/ENTITY_ADD_FAILURE';

//add response
export const RESPONSE_ADD = 'BACKEND/Tutorial/RESPONSE_ADD';
export const CHANGE_RESPONSE = 'BACKEND/Tutorial/CHANGE_RESPONSE';

export const RESPONSE_ADD_REQUEST = 'BACKEND/Tutorial/RESPONSE_ADD_REQUEST';
export const RESPONSE_ADD_SUCCESS = 'BACKEND/Tutorial/RESPONSE_ADD_SUCCESS';
export const RESPONSE_ADD_FAILURE = 'BACKEND/Tutorial/RESPONSE_ADD_FAILURE';

//add response detail
export const RESPONSE_DETAIL_ADD = 'BACKEND/Tutorial/RESPONSE_DETAIL_ADD';
export const CHANGE_RESPONSE_DETAIL = 'BACKEND/Tutorial/CHANGE_RESPONSE_DETAIL';

export const RESPONSE_DETAIL_CHANGE_TEXT = 'BACKEND/Tutorial/RESPONSE_DETAIL_CHANGE_TEXT';
export const RESPONSE_DETAIL_CHANGE_IMAGE = 'BACKEND/Tutorial/RESPONSE_DETAIL_CHANGE_IMAGE';
export const RESPONSE_DETAIL_CHANGE_TYPE = 'BACKEND/Tutorial/RESPONSE_DETAIL_CHANGE_TYPE';

export const RESPONSE_DETAIL_ADD_REQUEST = 'BACKEND/Tutorial/RESPONSE_DETAIL_ADD_REQUEST';
export const RESPONSE_DETAIL_ADD_SUCCESS = 'BACKEND/Tutorial/RESPONSE_DETAIL_ADD_SUCCESS';
export const RESPONSE_DETAIL_ADD_FAILURE = 'BACKEND/Tutorial/RESPONSE_DETAIL_ADD_FAILURE';

export const CHANGE_IS_ENABLE_ADD_RESPONSE = 'BACKEND/Tutorial/CHANGE_IS_ENABLE_ADD_RESPONSE';
export const CHANGE_IS_ENABLE_ADD_RESPONSE_DETAIL = 'BACKEND/Tutorial/CHANGE_IS_ENABLE_ADD_RESPONSE_DETAIL';

// load response
export const LOAD_RESPONSE_REQUEST = 'BACKEND/Tutorial/LOAD_RESPONSE_REQUEST';
export const LOAD_RESPONSE_SUCCESS = 'BACKEND/Tutorial/LOAD_RESPONSE_SUCCESS';
export const LOAD_RESPONSE_FAILURE = 'BACKEND/Tutorial/LOAD_RESPONSE_FAILURE';

// redirect to home chat
export const REDIRECT_TO_HOME_CHAT = 'BACKEND/Tutorial/REDIRECT_TO_HOME_CHAT';

//valid
export const VALID_REQUEST = 'BACKEND/Tutorial/VALID_REQUEST';

export const ADD_DEFAULT_INTENT = 'BACKEND/Tutorial/ADD_DEFAULT_INTENT';


export const ADD_DEFAULT_PATTERN = 'BACKEND/Tutorial/ADD_DEFAULT_PATTERN';

export const UPLOAD_RESPONSE_DETAIL_IMAGE_REQUEST = 'BACKEND/Tutorial/UPLOAD_RESPONSE_DETAIL_IMAGE_REQUEST';
export const UPLOAD_RESPONSE_DETAIL_IMAGE_SUCCESS = 'BACKEND/Tutorial/UPLOAD_RESPONSE_DETAIL_IMAGE_SUCCESS';
export const UPLOAD_RESPONSE_DETAIL_IMAGE_FAILURE = 'BACKEND/Tutorial/UPLOAD_RESPONSE_DETAIL_IMAGE_FAILURE';
